name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bae6c8a0afdf078f778b876a114c805d2accc177bfecf14ac24969fd546f559f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
