name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf8586a483df607c055f6925a5d762c73e9dd6512fa23786f3b01f29bde99bf6"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
