name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22885c1c15b48b065f43e4d7bd39d0f8b2a013f576f534d17cac0a688e3f3d40"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
