name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "267b2158dff20859a9fd9913dc546aa51632f9fda89ddf59d962fe317f975ff4"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
