name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "386a76861456a7b10a6399f1034ab7691d931324869b26c9d7fb10c7b32e2288"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
