name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af836f2f2d84e3146959c1bf4bc78b566dd363ac8572881a0ad31b4e2ec1b704"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
