name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fdc105ea7f06090d33b792235e62b6babe30c489b3b70c05947530c7f864bbc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
