name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dbb3d835caf726e933b53a51b2aca0c8c6a98e549f0ff328020a23148a5322c"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
