name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f62a2ea01a669854d9f9e798c1a45e76c42df338aaaa99948f4735774c85146b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
