name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e9e0e9fbc2749cc46cec764ff15075588f1465d49a0bbb687526100c4f8c6a8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
