name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f6a98529865715cc710fd5392bcf94ae7b9ee4c0f8855d4d304ddf4f9d5994f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
