name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "686f6bccd5502634a6e01db6c41f7f2197998ee2923a686df5cc5c7e1a3cd981"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
