name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c17d768ca8f6dd126fb75221cb3ab2777697b056aa89710db33844fcdfea42f1"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
