name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4b885c160d8594fc433672946f6b3642207aaf44f6e09475c16dac4f0bd8b2e"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
