name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d5c769b3ffc3d8a18a2f7c61d3c3903b118be36aeff9be286a359730644eb98"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
