name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daa2aa26d4a82384f0d62280744fa9bd552404aabf0abfc21ef318bc203b62e5"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
