name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d6de4517882240c14657e4a483d88f8776b32ea8cd6123536f6b9857fd0e0f0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
