name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "878378a413fef251a61839880a79ebb47e4d1d15c173c10a102f25647602bef2"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
