name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68937e2989a5953fb820a7831427731afea0ab5d0029860d189af45adf9cca81"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
