name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67de21c9f7db1818a624b6e3479de458c574030ffd7bacfb8dc3a0e77e49dfa6"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
