name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "343e1a8cf1827ddacf6d150515b93e40fe8e547c63b682b1a127452187e685d1"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
