name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20e79c52134deb548682d47f610ce54dd7137fb2573ca5090b7e8bb1bc9d094e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
