name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a6ba5123496ed838a0ea66931497e6aac5f04718fcd8556ac7cd19dbd509a02"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
