name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e432c0b9f6b637bb9995a93b7a1af1341320b0f3dc039cdd408d8dd106718f35"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
