name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3763764c76247076149a752b2fb150b97dc23d1568c0f67d83f2d1c5b07126e"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
