name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f137d541c561c1f32bdf89b148283ecafa24e46a1324adc394a63e43f6990a3d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
