name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c0dec43506b43ab0d898871f78739a7a15351251c969718e35c46e9a4981273"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
