name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a87c07d985473075b37f1c250016083be70a691a2a025ce8ec1cf1a86a50696d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
