name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddf4f922bad5d2240ff72bfbf192c0cf54ee3f01b3b15181ce60cb4ba3c01bac"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
