name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6df7101d24d9f54e18e8c801c28dcb7befc1b7bd8c03bc3dcd781ea803782d76"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
