name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ae60c0a41d0df578dbb67f56ceb424dd84da80a46dfa739aca2a26f8bcd8c1c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
