name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fda35cca5991ffe83769b09a15805d695960c68accc77385cd51d9fca42f783"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
