name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c334beb11b9e32b5aaad60bafc0d4f92123c0869ba7fc497a65c508ae1d751cf"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
