name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7be0461649094094e7fc823044dc59b7dbde667ae2ea9810f51bb3e848e14e28"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
