name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60875a88f924e02e4c0eefca959cf5fa032ac757220dfdf5b9cc941ad1806789"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
