name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e75933e55f8e4a0cff95d8bbbd745a17e2a32e1b53ce4237ba2c60c3a1269950"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
