name = "VoodooPack 2"
author = "VoodooFrog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccec072ca9111d3bac81c5a86350c4811e98812597186987c45135aee7b76f64"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
